apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: film-locations
  name: film-locations
spec:
  replicas: 3
  selector:
    matchLabels:
      app: film-locations
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: film-locations
    spec:
      containers:
      - image: kmpolakowski/film-locations-service
        name: film-locations-service
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: film-locations
  name: film-locations
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: film-locations
  type: LoadBalancer
status:
  loadBalancer: {}
